package libdwarf;
import com.ochafik.lang.jnaerator.runtime.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class Dwarf_Cmdline_Options extends Structure<Dwarf_Cmdline_Options, Dwarf_Cmdline_Options.ByValue, Dwarf_Cmdline_Options.ByReference > {
	/** C type : Dwarf_Bool */
	public int check_verbose_mode;
	public Dwarf_Cmdline_Options() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("check_verbose_mode");
	}
	/** @param check_verbose_mode C type : Dwarf_Bool */
	public Dwarf_Cmdline_Options(int check_verbose_mode) {
		super();
		this.check_verbose_mode = check_verbose_mode;
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected Dwarf_Cmdline_Options newInstance() { return new Dwarf_Cmdline_Options(); }
	public static Dwarf_Cmdline_Options[] newArray(int arrayLength) {
		return Structure.newArray(Dwarf_Cmdline_Options.class, arrayLength);
	}
	public static class ByReference extends Dwarf_Cmdline_Options implements Structure.ByReference {
		
	};
	public static class ByValue extends Dwarf_Cmdline_Options implements Structure.ByValue {
		
	};
}
