package libdwarf;
import com.ochafik.lang.jnaerator.runtime.Structure;
import com.sun.jna.Pointer;
import java.util.Arrays;
import java.util.List;
import libdwarf.LibdwarfLibrary.dwarf_printf_callback_function_type;
/**
 * <i>native declaration : line 3360</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class Dwarf_Printf_Callback_Info_s extends Structure<Dwarf_Printf_Callback_Info_s, Dwarf_Printf_Callback_Info_s.ByValue, Dwarf_Printf_Callback_Info_s.ByReference > {
	/** C type : void* */
	public Pointer dp_user_pointer;
	/** C type : dwarf_printf_callback_function_type */
	public dwarf_printf_callback_function_type dp_fptr;
	/** C type : char* */
	public Pointer dp_buffer;
	public int dp_buffer_len;
	public int dp_buffer_user_provided;
	/** C type : void* */
	public Pointer dp_reserved;
	public Dwarf_Printf_Callback_Info_s() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("dp_user_pointer", "dp_fptr", "dp_buffer", "dp_buffer_len", "dp_buffer_user_provided", "dp_reserved");
	}
	/**
	 * @param dp_user_pointer C type : void*<br>
	 * @param dp_fptr C type : dwarf_printf_callback_function_type<br>
	 * @param dp_buffer C type : char*<br>
	 * @param dp_reserved C type : void*
	 */
	public Dwarf_Printf_Callback_Info_s(Pointer dp_user_pointer, dwarf_printf_callback_function_type dp_fptr, Pointer dp_buffer, int dp_buffer_len, int dp_buffer_user_provided, Pointer dp_reserved) {
		super();
		this.dp_user_pointer = dp_user_pointer;
		this.dp_fptr = dp_fptr;
		this.dp_buffer = dp_buffer;
		this.dp_buffer_len = dp_buffer_len;
		this.dp_buffer_user_provided = dp_buffer_user_provided;
		this.dp_reserved = dp_reserved;
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected Dwarf_Printf_Callback_Info_s newInstance() { return new Dwarf_Printf_Callback_Info_s(); }
	public static Dwarf_Printf_Callback_Info_s[] newArray(int arrayLength) {
		return Structure.newArray(Dwarf_Printf_Callback_Info_s.class, arrayLength);
	}
	public static class ByReference extends Dwarf_Printf_Callback_Info_s implements Structure.ByReference {
		
	};
	public static class ByValue extends Dwarf_Printf_Callback_Info_s implements Structure.ByValue {
		
	};
}
