package libdwarf;
import com.ochafik.lang.jnaerator.runtime.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : line 537</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class Dwarf_P_String_Attr_s extends Structure<Dwarf_P_String_Attr_s, Dwarf_P_String_Attr_s.ByValue, Dwarf_P_String_Attr_s.ByReference > {
	/**
	 * Offset of string attribute data<br>
	 * C type : Dwarf_Unsigned
	 */
	public long sa_offset;
	/** C type : Dwarf_Unsigned */
	public long sa_nbytes;
	public Dwarf_P_String_Attr_s() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("sa_offset", "sa_nbytes");
	}
	/**
	 * @param sa_offset Offset of string attribute data<br>
	 * C type : Dwarf_Unsigned<br>
	 * @param sa_nbytes C type : Dwarf_Unsigned
	 */
	public Dwarf_P_String_Attr_s(long sa_offset, long sa_nbytes) {
		super();
		this.sa_offset = sa_offset;
		this.sa_nbytes = sa_nbytes;
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected Dwarf_P_String_Attr_s newInstance() { return new Dwarf_P_String_Attr_s(); }
	public static Dwarf_P_String_Attr_s[] newArray(int arrayLength) {
		return Structure.newArray(Dwarf_P_String_Attr_s.class, arrayLength);
	}
	public static class ByReference extends Dwarf_P_String_Attr_s implements Structure.ByReference {
		
	};
	public static class ByValue extends Dwarf_P_String_Attr_s implements Structure.ByValue {
		
	};
}
